[workspace]
authors = ["longred <longredzhong@outlook.com>"]
channels = ["conda-forge"]
name = "Wan2GP"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
extra-index-urls = [
    "https://pypi.mirrors.ustc.edu.cn/simple",
    "https://pypi.python.org/simple",
]

[tasks]

[dependencies]
python = "3.10.*"
ffmpeg = ">=7.1.1,<8"
librosa = ">=0.11.0,<0.12"
av = ">=15.0.0,<16"

[pypi-dependencies]
torch = { version = ">=2.7.1, <3", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.22.1, <0.23", index = "https://download.pytorch.org/whl/cu128" }
torchaudio = { version = ">=2.7.1, <3", index = "https://download.pytorch.org/whl/cu128" }
pydantic = ">=2.11.7, <3"
mmgp = ">=3.5.1, <4"
easydict = ">=1.13, <2"
einops = ">=0.8.1, <0.9"
omegaconf = ">=2.3.0, <3"
safetensors = ">=0.5.3, <0.6"
soundfile = ">=0.13.1, <0.14"
tqdm = ">=4.67.1, <5"
transformers = ">=4.53.2, <5"
diffusers = ">=0.34.0, <0.35"
opencv-python-headless = ">=4.12.0.88, <5"
imageio = ">=2.37.0, <3"
ftfy = ">=6.3.1, <7"
decord = ">=0.6.0, <0.7"
rembg = { version = ">=2.0.67, <3", extras = ["gpu"] }
ffmpeg-python = ">=0.2.0, <0.3"
sentencepiece = ">=0.2.0, <0.3"
gradio = ">=5.38.0, <6"
timm = ">=1.0.17, <2"
segment-anything = ">=1.0, <2"
hydra-core = ">=1.3.2, <2"
matplotlib = ">=3.10.3, <4"
loguru = ">=0.7.3, <0.8"
